import Header from "@/Shared/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import ReduxProvider from "@/Providers/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Header></Header>

          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
